# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b228d86f068dfeeb1ef47ad16ee653fb94f88ab1373d63dc3fbba0e9bca2ce931ae23f7c2ad5cad041fba84c0e317bebade11dcca87841c5305d2f61c789e2a2

test:
  secret_key_base: cd2b9e254106b240f9ebceb8ec068b33da23340ca87d4f5e017c489e0e80cde83d6a06dd168bff309489c3e2dc070a7d3038195014c726ca320331c57b62a0bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
